# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud-connection'
    organization: 'eoingalvin2'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner,
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=eoingalvin2_PetClinic
      sonar.projectName=PetClinic

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    pmdRunAnalysis: true 
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**/target/spring-boot-docker.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'mavenBuildArtifact'
    publishLocation: 'Container'
- task: Docker@2
  inputs:
    containerRegistry: 'dockerHub'
    repository: 'eoingalvin2 / eoinpetclinic1'
    command: 'build'
    Dockerfile: '/**/DockerFile'
- task: Docker@2
  inputs:
    containerRegistry: 'dockerHub'
    repository: 'eoingalvin2 / eoinpetclinic1'
    command: 'push'
- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: 'Azure for Students (d6bc2b19-a9f0-4ec3-a145-4a25893ce50f)'
    Action: 'Start Azure App Service'
    WebAppName: 'eoinDocker'
    SpecifySlotOrASE: true
    ResourceGroupName: 'EoinResourceGroup'
    Slot: 'production'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students (d6bc2b19-a9f0-4ec3-a145-4a25893ce50f)'
    appType: 'webAppContainer'
    WebAppName: 'eoinDocker'
    DockerNamespace: 'eoingalvin2'
    DockerRepository: 'eoinpetclinic1'
    DockerImageTag: '$(Build.BuildId)'
    StartupCommand: 'java -jar target/spring-boot-docker'